// THE EMAIL SEAM (Stage 10S). SERVER-ONLY.
//
// The site is static and database-free. Lead forms email their submissions through AWS SES v2
// (region us-east-2, chosen for vendor consolidation under the company AWS account) and NOTHING is
// stored. This is the ONLY module that talks to SES — changing vendors later means editing just
// this file.
//
// SERVER-ONLY GUARD. This module reads secret credentials and must never reach a client bundle. It
// is imported ONLY by the "use server" action (src/app/actions/leads.ts), which Next.js never ships
// to the browser. We ALSO assert it at runtime (below) instead of adding the `server-only` npm
// package, because Stage 10S permits exactly ONE new dependency (@aws-sdk/client-sesv2) and a second
// package — even a build-time shim — would break that budget. The @aws-sdk import also pulls Node
// built-ins, so an accidental client import fails to bundle regardless.
import { SESv2Client, SendEmailCommand } from "@aws-sdk/client-sesv2";
import { SITE } from "@/lib/site";
import type { LeadKind } from "@/lib/leads";
import { clean, buildSubject } from "@/lib/leadSanitize";

if (typeof window !== "undefined") {
  throw new Error("src/lib/mail.ts is server-only and must never be imported into client code.");
}

// Addresses derive from the canonical domain (no hardcoded literal). us-east-2 mailbox routing:
//   notification (system of record) → providers@ (applications) / info@ (contact messages)
//   notification From              → no-reply@ (unmonitored; replies go to the submitter via ReplyTo)
//   auto-ack From                  → info@ (a monitored address the submitter can reply to)
const DOMAIN = new URL(SITE.domain).hostname;
const ADDR = {
  noReply: `no-reply@${DOMAIN}`,
  info: SITE.email, // the ack From = the canonical public email (single source), not a reconstructed literal
  providers: `providers@${DOMAIN}`,
} as const;

function notificationTo(kind: LeadKind): string {
  return kind === "provider" ? ADDR.providers : ADDR.info;
}

// A labeled field for the notification body.
export type LeadField = { label: string; value: string };

export type LeadPayload = {
  kind: LeadKind;
  name: string; // for the subject + the ack greeting
  email: string; // the submitter's address → ReplyTo on the notification, To on the ack
  fields: ReadonlyArray<LeadField>; // every submitted field, labeled, in display order
  sourcePage: string; // e.g. "/apply"
  submittedAt: string; // ISO 8601, generated by the action at acceptance
};

export type MailResult = { ok: true } | { ok: false; reason: "unavailable" | "send_failed" };

// Read credentials AT CALL TIME (never at import) so a missing env var yields a typed friendly
// failure, never a crash and never a faked success.
type SesConfig = { region: string; accessKeyId: string; secretAccessKey: string };
function readConfig(): SesConfig | null {
  const region = process.env.AWS_SES_REGION;
  const accessKeyId = process.env.AWS_ACCESS_KEY_ID;
  const secretAccessKey = process.env.AWS_SECRET_ACCESS_KEY;
  if (!region || !accessKeyId || !secretAccessKey) return null;
  return { region, accessKeyId, secretAccessKey };
}

// Lazy, module-scoped client — created on first successful config read, reused after.
let client: SESv2Client | null = null;
function getClient(cfg: SesConfig): SESv2Client {
  if (!client) {
    client = new SESv2Client({
      region: cfg.region,
      credentials: { accessKeyId: cfg.accessKeyId, secretAccessKey: cfg.secretAccessKey },
    });
  }
  return client;
}

// Plain-text ONLY (no HTML anywhere) → zero HTML-injection surface. Every value is clean()'d; the
// structural lines (labels, source, timestamp) are literals we control.
function notificationBody(p: LeadPayload): string {
  const heading =
    p.kind === "provider"
      ? "New provider application from the Nexo Access website."
      : "New contact message from the Nexo Access website.";
  const lines = [
    heading,
    "",
    ...p.fields.map((f) => `${f.label}: ${clean(f.value) || "(not provided)"}`),
    "",
    `Source page: ${clean(p.sourcePage)}`,
    `Submitted (UTC): ${p.submittedAt}`,
  ];
  return lines.join("\n");
}

// Auto-ack: brief, professional, §7.2-compliant — soft assurance, NO response-time promise, one
// what-happens-next line per kind, zero marketing.
function ackSubject(kind: LeadKind): string {
  return kind === "provider"
    ? "Nexo Access: we received your application"
    : "Nexo Access: we received your message";
}

// The ack carries NO submitter-supplied text (fixed greeting, no name) — so even though it goes to a
// submitter-controlled address, no attacker-chosen content is ever reflected out through our domain.
function ackBody(kind: LeadKind): string {
  const whatNext =
    kind === "provider"
      ? "We’ll review your details and follow up about running trips with us."
      : "We’ll read your note and follow up about your program.";
  return [
    "Hello,",
    "",
    "Thanks for reaching out to Nexo Access. We’ve received your message.",
    whatNext,
    "",
    "If you need to add anything, just reply to this email.",
    "",
    "The Nexo Access team",
    DOMAIN,
  ].join("\n");
}

function simpleEmail(args: {
  from: string;
  to: string;
  replyTo?: string;
  subject: string;
  body: string;
}): SendEmailCommand {
  return new SendEmailCommand({
    FromEmailAddress: args.from,
    Destination: { ToAddresses: [args.to] },
    ReplyToAddresses: args.replyTo ? [args.replyTo] : undefined,
    Content: {
      Simple: {
        Subject: { Data: args.subject, Charset: "UTF-8" },
        Body: { Text: { Data: args.body, Charset: "UTF-8" } },
      },
    },
  });
}

// Per-recipient auto-ack cooldown. The ack is best-effort and goes to a submitter-SUPPLIED address, so
// we cap how often ANY single address can be acked — this blunts using the ack as a reflection/bombing
// relay (a victim's inbox can't be flooded by repeat submissions), independent of the per-IP throttle in
// the action. Bounded in size so spoofed floods can't grow memory. Per-instance + best-effort, like the
// throttle. (Date.now() is fine here: real server runtime, not a workflow sandbox.)
const ACK_COOLDOWN_MS = 10 * 60 * 1000; // 10 min
const ackSeen = new Map<string, number>();
function ackAllowed(addr: string): boolean {
  const now = Date.now();
  if (ackSeen.size > 5_000) {
    ackSeen.forEach((t, k) => {
      if (now - t > ACK_COOLDOWN_MS) ackSeen.delete(k);
    });
    if (ackSeen.size > 5_000) ackSeen.clear();
  }
  const last = ackSeen.get(addr);
  if (last && now - last < ACK_COOLDOWN_MS) return false;
  ackSeen.set(addr, now);
  return true;
}

// Send the two lead emails. Contract:
//   (a) NOTIFICATION is the SYSTEM OF RECORD — its success IS the form's success.
//   (b) AUTO-ACK is BEST-EFFORT — its failure NEVER fails the form (this absorbs SES-sandbox rejects
//       of an unverified submitter address). We log and continue.
export async function sendLeadEmails(p: LeadPayload): Promise<MailResult> {
  const cfg = readConfig();
  if (!cfg) {
    console.warn("[mail] SES env not configured — lead email not sent (returning 'unavailable').");
    return { ok: false, reason: "unavailable" };
  }

  const ses = getClient(cfg);
  const subject = buildSubject(p.kind === "provider" ? "Apply" : "Contact", p.name);
  const replyTo = clean(p.email);

  // (a) NOTIFICATION — awaited; its failure fails the form.
  try {
    await ses.send(
      simpleEmail({
        from: ADDR.noReply,
        to: notificationTo(p.kind),
        replyTo: replyTo || undefined,
        subject,
        body: notificationBody(p),
      }),
    );
  } catch (err) {
    // Log server-side only; the action maps this to a generic friendly message (no detail leak).
    console.error("[mail] notification send failed:", err instanceof Error ? err.message : String(err));
    return { ok: false, reason: "send_failed" };
  }

  // (b) AUTO-ACK — best-effort. Skip if we have no deliverable address OR this address was acked
  //     recently (per-recipient cooldown blunts reflection/bombing). Swallow any failure.
  if (replyTo && ackAllowed(replyTo.toLowerCase())) {
    try {
      await ses.send(
        simpleEmail({
          from: ADDR.info,
          to: replyTo,
          subject: ackSubject(p.kind),
          body: ackBody(p.kind),
        }),
      );
    } catch (err) {
      console.warn(
        "[mail] auto-ack not delivered (non-fatal):",
        err instanceof Error ? err.message : String(err),
      );
    }
  }

  return { ok: true };
}
